/*
 *
 *    Copyright (c) 2026 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//! Core IDL parsing and code generation library for rs-matter.
//!
//! This crate contains the Matter IDL parser and Rust code generator,
//! extracted from the proc-macro crate so it can be used from build.rs scripts.

use std::path::Path;

use idl::{cluster_content, globals, Idl, IdlGenerateContext, CSA_STANDARD_CLUSTERS_IDL_V1_5_1_0};

// FIXME: With rust 1.92 the compiler emits an unused assignment lint, because
//        of the code generated by miette-derive. See https://github.com/zkat/miette/issues/458
#[allow(unused_assignments)]
mod idl;

fn format_tokens(tokens: proc_macro2::TokenStream) -> String {
    let file = syn::parse2(tokens).expect("Generated code is not valid Rust");
    prettyplease::unparse(&file)
}

/// Generate Rust code for all Matter clusters from the latest IDL specification.
///
/// Produces a multi-file output:
/// - `dest_dir/clusters_generated.rs` — root module with globals and `pub mod` declarations
/// - `dest_dir/clusters_generated/*.rs` — one file per cluster
///
/// The `rs_matter_crate` parameter controls how the generated code refers to
/// the rs-matter crate (e.g. `"crate"` when called from rs-matter's own build.rs,
/// or `"rs_matter"` when used by external crates).
pub fn generate(rs_matter_crate: &str, dest_dir: &Path) {
    generate_filtered(rs_matter_crate, dest_dir, None);
}

/// Like [`generate`], but optionally restricts code generation to a subset of
/// clusters, matched by their generated snake_case module name (e.g. `on_off`,
/// `level_control`). `only = None` generates every cluster, exactly like
/// [`generate`]; `only = Some(&[...])` emits only the listed clusters.
///
/// The `globals` module is always generated regardless of the filter.
///
/// Why filter: the full Matter IDL expands to ~670k lines of Rust across 142
/// clusters, and rustc compiling all of it is what drives peak build RAM into
/// the multi-GB range. A typical device needs only a few dozen clusters.
/// Generated cluster modules reference only `crate::` items and `decl::globals`
/// — never each other — so any subset compiles standalone. The caller must
/// include every cluster that the rs-matter core itself references internally
/// (e.g. `operational_credentials`, `network_commissioning`, `time_synchronization`),
/// otherwise rs-matter will fail to compile with "module not found".
pub fn generate_filtered(rs_matter_crate: &str, dest_dir: &Path, only: Option<&[&str]>) {
    let idl_file = CSA_STANDARD_CLUSTERS_IDL_V1_5_1_0;

    let idl = match Idl::parse(idl_file.into()) {
        Ok(result) => result,
        Err(e) => {
            let span_bytes = &idl_file.as_bytes()[e.error_location.offset()..];
            panic!(
                "Parser failed with {:?}, at\n===\n{}\n===\n",
                e,
                String::from_utf8_lossy(&span_bytes[..span_bytes.len().min(256)])
            );
        }
    };

    let context = IdlGenerateContext::new(rs_matter_crate);

    // Create the clusters_generated/ directory
    let clusters_dir = dest_dir.join("clusters_generated");
    std::fs::create_dir_all(&clusters_dir).unwrap();

    // Generate globals
    let globals_code = globals(&idl.globals, &context);

    // Generate each cluster as a separate file
    let mut cluster_files = Vec::new();

    for c in &idl.clusters {
        let (module_name, content) = cluster_content(c, &idl.globals, &context);

        // Skip clusters not in the whitelist. We compute `module_name` (cheap)
        // before the expensive prettyplease formatting + file write below, so a
        // filtered build only pays the formatting cost for the kept clusters.
        if let Some(only) = only {
            if !only.contains(&module_name.as_str()) {
                continue;
            }
        }

        let formatted = format_tokens(content);
        let file_path = clusters_dir.join(format!("{module_name}.rs"));
        std::fs::write(&file_path, formatted).unwrap();

        cluster_files.push((module_name, file_path.to_string_lossy().to_string()));
    }

    // Generate root module: globals + per-cluster mod declarations with #[path] attributes
    let globals_formatted = format_tokens(globals_code);

    let mut root = String::from("// IDL-generated code (via build.rs):\n\n");
    root.push_str(&globals_formatted);
    root.push('\n');

    for (module_name, _file_path) in &cluster_files {
        root.push_str(&format!(
            "/// Generated cluster module\n\
             #[allow(async_fn_in_trait)]\n\
             #[allow(unknown_lints)]\n\
             #[allow(clippy::uninlined_format_args)]\n\
             #[allow(unexpected_cfgs)]\n\
             pub mod {} {{\n\
                 include!(concat!(env!(\"OUT_DIR\"), \"/clusters_generated/{}.rs\"));\n\
             }}\n\n",
            module_name, module_name
        ));
    }

    std::fs::write(dest_dir.join("clusters_generated.rs"), root).unwrap();
}
